#!/usr/bin/env python3
"""
ทดสอบ generate รายงาน DOCX บนเครื่อง (ไม่ต้อง deploy)
ใช้: python test_report_local.py
จะสร้างไฟล์ test_report_en.docx และ test_report_th.docx ในโฟลเดอร์ปัจจุบัน
"""
import io
import os
import sys

# ใช้ src/report_core
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))
from report_core import (
    ReportData,
    CategoryResult,
    FirstImpressionData,
    build_docx_report,
)

def main():
    report = ReportData(
        client_name="input",
        analysis_date="2026-01-03",
        video_length_str="02:05",
        overall_score=70,
        categories=[
            CategoryResult("Engaging", " engaging", 75, "high", 15, 20, ""),
            CategoryResult("Confidence", "confidence", 65, "moderate", 13, 20, ""),
            CategoryResult("Authority", "authority", 55, "low", 11, 20, ""),
        ],
        summary_comment="",
        generated_by="Generated by AI People Reader™",
        first_impression=FirstImpressionData(
            eye_contact_pct=85.0,
            upright_pct=78.0,
            stance_stability=82.0,
        ),
    )

    for lang, name in [("en", "test_report_en.docx"), ("th", "test_report_th.docx")]:
        bio = io.BytesIO()
        build_docx_report(
            report,
            bio,
            graph1_path="",
            graph2_path="",
            lang=lang,
            report_style="operation_test",
        )
        with open(name, "wb") as f:
            f.write(bio.getvalue())
        print(f"Created: {name}")

if __name__ == "__main__":
    main()
